*portions of this notebook were adapted from [Mark Krumholz's public course notes](https://sites.google.com/a/ucsc.edu/krumholz/teaching-and-courses/)*

# Lab 1 -  First Steps in Python

## Lab 1 Contents

1. Jupyter
   * Jupyter Intro
   * Jupyter cautions
2. Using Jupyter as a calculator
3. Variables
4. Arrays
    * Defining arrays
    * Array manipulation
    * Multidimensional arrays
    * Array attributes
   
***Each section 1-4 of this notebook contains an exercise that you must complete.***

## 1. Jupyter

### 1.1 Jupyter Intro

Jupyter notebooks have two kinds of cells. Markdown cells like this one have no labeling to the left of the cell, and, when executed, appear as ordinary text. Code cells like the one below have In [ ]: printed to the side of them and, when executed, a number appears inside of the brackets. To execute a cell of either type in Jupyter, hit shift + enter inside of that cell. Try it by double clicking on this cell and hitting shift + enter, and then do the same with the code cell below. Note that a markdown cell becomes pure text when you execute it, while a code cell spits out some output labelled Out [ ]:.


In [1]:
1+2

3

The guts of Jupyter is the coding language Python, and any and all Python syntax will work inside of code cells. However, Jupyter code cells also have some extra capabilities, which we will talk about as needed in the future.

A key feature of Jupyter is that it integrates markdown (instructions/notes), code ***and*** output all in the same document. For this reason, many astronomers, including myself, use Jupyter as a sort of lab notebook rather than maintaining lab notes, code, and code output all in separate documents.

### 1.2 Jupyter Cautions

You should always keep in mind that ***cells within a Jupyter notebook can be executed and reexecuted in any order*** as this can sometimes get you into trouble. This feature is the reason why an executed code cell is numbered, so that you know what order the cells you see have been executed in. Note that this does not have to be linear from the top to the bottom of the document, but can jump around within it. Often, you will note a mistake or something that you want to try and will go back and change the code in an earlier cell. If you reexecute just this one cell, then any already executed cells that rely on variables defined in the reexecuted cell or its output will ***not*** be automatically updated.  

For the purposes of this class, labs and homeworks should always be executable in a linear fashion, as you will be clearing all output before submitting them. For this reason, you should observe the following "best practices" for coding in notebooks.

1. Use descriptive variable labels (e.g. lum_stara = , mass_starb =) and create a new variable name each time you do a calculation. ***Do not reuse variable names*** or you risk getting a nonsense answer when you refer to that variable.

2. Before handing in any lab or homework, restart the notebook and execute the whole thing from start to finish once, making sure that all of your code output is how you want it. Note that **restarting the kernel will clear the code output, not the code itself**, so you will not be losing your work.

3. If you note a mistake in an earlier cell and go back to correct it, you should be careful to also reexecute any cells that depend on it. If you want to do a calculation similar to one that you executed in a previous cell, you should instead copy the contents of that cell into a new cell, rename the variables, and execute it again.


<div class=hw>

### Exercise 1
-------------

Many common operations also have keyboard shortcuts. To see a full list of them, click the search button (third option) on the bar to the far left and scroll through the commands.

a. Change this cell to a markdown cell

<div class=hw>
b. Insert a blank code cell above this one, and one below as well.

<div class=hw>
c. Split the cell below in between the two operations so that each appears in its own separate cell, and then execute both cells.

In [2]:
1+2

3

In [3]:
1+3

4

<div class=hw>
d. Delete the cell below

I've also posted on Moodle a cheat sheet for syntax within markdown cells, which can be accessed __[here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)__. Use this to complete the following tasks.

e. *Make this text italic.*

f. **Make this text bold.**

g. ***Make this text bold and italic.***

h. # Make this a heading.

i. [Make this a hyperlink to your favorite webpage.](https://open.spotify.com/intl-ja/artist/4UK2Lzi6fBfUi9rpDt6cik?si=1XNGGry3RyGDQuqnanY6Bg)

j. Insert a picture of your favorite astronomical object inline here.
![alt text](https://www.cfa.harvard.edu/sites/default/files/styles/max_650x650/public/2019-04/GalaxyClusters_2.jpg?itok=Plqik-eY)

k. Insert the file logo.png from the Google Drive Homework00 folder inline here
![alt text](Logo.png)

l. Make the asterisks in the following sentence visible: I \*love\* astronomy


There are obviously lots of other things that you can do, but these are the basics that you'll use the most often.

## 2. Using jupyter as a calculator

In Jupyter notebooks, every cell is a command prompt into which we can enter python commands. One very basic way to use python is as a calculator.

Python knows the basic arithmetic operations plus (+), minus (-), times (\*), divide (/), and raise to a power (\**).

*Sidenote*
Note that if you double click on this cell, you'll see that I've inserted a BACKSLASH (\) before the asterisks. That is because the asterisk has special meaning inside of a markdown cell. Single asterisks make an item *italicized* when you execute the cell, and double asterisks make it **bold**. This is ***NOT*** the case for code cells.  

Execute all of the cells below and make sure that you understand what they're doing before moving on.

In [4]:
2+3

5

In [5]:
2*3

6

In [6]:
2-3

-1

In [7]:
2/3

0.6666666666666666

In [8]:
2**3

8

It also understands parentheses, and follows the normal rules for order of operations:

In [9]:
1+2*3

7

In [10]:
1+2**3

9

In [11]:
(1+2)*3

9

<div class=hw>

### Exercise 2
-------------

Execute the calculations shown below in python. Use the code cells below each expression.

x = 2.5x10$^4$   
y = 8.1x10$^3$

a. $x+y$  

In [12]:
x=2.5*10**4
y=8.1*10**3

x+y

33100.0

<div class=hw>
b. $x^3$  

In [13]:
x**3

15625000000000.0

<div class=hw>
c. $\sqrt{y}$  

In [14]:
y**(1/2)

90.0

<div class=hw>
d. $\frac{3x+y^2}{2}$

In [15]:
(3*x+y**2)/2

32842500.0

## 3. Simple variables

We can also define variables to store numbers, and we can perform arithmetic on those variables. Variables are just names for boxes that can store values, and on which you can perform various operations. For example, execute each of the cells below and make sure you understand the output:

In [16]:
a=4

In [17]:
a+1

5

In [18]:
a/2

2.0

In [19]:
a=a+1

In [20]:
a

5

In [21]:
a**2

25

Note that the line a=a+1 redefined the variable as one greater than it was before. This is a simple example of how not using a new variable name could get you into trouble (if you were to assume that a was still 4). Note too that lines in which you have defined a variable do not have any output by default. If you want to check that the variable is properly assigned or see its value, you can type the variable name alone on a line below the variable assignment line.

In [22]:
a=10**2
a

100

There's also a subtle but important point to notice here, which is the meaning of the equal sign. In mathematics, the statement that a = b is a statement that two things are equal, and it can be either true or false. In python, as in almost all other programming languages, a = b means something different. It means that the value of the variable a should be changed to whatever value b has. Thus the statement we made a = a + 1 is not an assertion (which is obviously false) that a is equal to itself plus one. It is an instruction to the computer to take the variable a, and 1 to it, and then store the result back into the variable a. In this example, it therefore changes the value of a from 4 to 5.

One more point regrading assignments: the fact that = means something different in programming than it does in mathematics implies that the statements a = b and b = a will have very different effects. The first one causes the computer to forget whatever is stored in a and replace it by whatever is stored in b. The second statement has the opposite effect: the computer forgets what is stored in b, and replaces it by whatever is stored in a.

The variable a that we have defined is an integer, or int for short. We can find this out by asking python using one of its many built-in functions, namely "type".

In [23]:
b=5

In [24]:
type(b)

int

Integers are exactly what they sound like: they hold whole numbers, and operations involving them and other whole numbers will always yield whole numbers. This is an important point in general programming, because variable types are not generally reassigned dynamically. So, for example, the operation 5/2 would yield 2 rather than 2.5 if 5 is an integer. In our case, however, we are using Python 3, which will automatically convert an integer to the next type of variable if the natural output is not a whole number, as below :

In [25]:
b/2

2.5

If we assign this to a variable, we will have a new type of variable: a floating point number, or float for short. Note that after completing this operation, b is no longer an integer, as you can see using type.

unlike b, b/2 is ***not*** an integer, as you can see by creating a new variable, storing b/2 in it, and typing it.

In [26]:
c = b/2

In [27]:
c

2.5

In [28]:
type(c)

float

A floating point variable is capable of holding real numbers.

Why have different types of variables for integers versus non-integer real numbers? In mathematics there is no need to make the distinction, of course: all integers are real numbers, so it would seem that there should be no reason to have a separate type of variable to hold integers. However, this ignores the way computers work. On a computer, operations involving integers are exact: 1 + 1 is exactly 2. However, operations on real numbers are necessarily inexact. I say necessarily because a real number is capable of having an arbitrary number of decimal places. The number pi contains infinitely many digits, and never repeats, but my computer only comes with a finite amount of memory and processor power.

Even rational numbers (like 2/3) run into this problem, because their decimal representation (or to be exact their representation in binary) may be an infinitely repeating sequence. Thus it is not possible to perform operations on arbitrary real numbers to exact precision. Instead, arithmetic operations on floating point numbers are approximate, with the level of accuracy determined by factors like how much memory one wants to devote to storing digits, and how much processor time one wants to spend manipulating them.

On most computers a python floating point number is accurate to about 1 in 10^15, but this depends on both the architecture and on the operations you perform. That's enough accuracy for many purposes, but there are plenty of situations (for example counting things) when we really want to do things precisely, and we want 1 + 1 to be exactly 2. That's what integers are there for.

A third type of very useful variable is strings, abbreviated str. A string is a sequence of characters, and one can declare that something is a string by putting characters in quotation marks (either " or ' is fine):

In [29]:
d = "star"

In [30]:
type(d)

str

The quotation marks are important here. To see why, try issuing the command without them:

In [31]:
# d = star

This is an error message, complaining that the computer doesn't know what star is. The problem is that, without the quotation marks, python thinks that star is the name of a variable, and complains when it can't find a variable by that name. Putting the quotation marks tells python that we mean a string, not a variable named star.

***Note that in instructions we will frequently give you "broken" cells like the one above. Make sure to remove or comment these out before handing in your notebook so that it will run***

Obviously we can't add strings in the same sense that we add numbers, but we can still do operations on them. The plus operation concatenates two strings together:

In [32]:
e = "planet"

In [33]:
d+e

'starplanet'

In addition to integers, floats, and strings, there are three other types of variables worth mentioning. The first is a Boolean variable (named after George Boole), which represents a logical value. Boolean variables can be either True or False:

In [34]:
g = True

In [35]:
type(g)

bool

Boolean variables can have logic operations performed on them. In particular, there are three logical operators that we care about: not, and, and or. Play around with the cells below (defining new variables to test your theories on if you wish) and see if you can figure out what each one does, and then describe it below.

In [36]:
not g

False

In [37]:
h = False

In [38]:
g and h

False

In [39]:
g or h

True

<div class=hw>

### Exercise 3
-------------

Double click here and edit the text below to describe what each operator does in your own wods

the NOT operator negates the statement and returns the other boolean from given.

the AND operator returns True if both statments are true

the OR operator returns True if at least one statement is true

## 4. Arrays

### 4.1 Defining Arrays

The variables we have dealt with so far are fairly simple. They represent single values. However, for scientific or numeric purposes we often want to deal with large collections of numbers. The basic tool for doing this is an array. Arrays are not part of the core python language, but they are part of a very commonly used code library called numpy. In order to invoke or load numpy in this environment, you will need to "import" it.

In [40]:
import numpy

Once loaded, you can take advantage of any numpy function (like the "type" function that is part of the python core language) by typing numpy.functionname. For example, the square root (sqrt) function:

In [41]:
numpy.sqrt(16)

np.float64(4.0)

As we will use numpy a lot, it is convenient to import it under a shorter name, as below. This can be anything really, but it's easiest to use something that will be easy to remember. The standard short name for numpy is np

In [42]:
import numpy as np

In [43]:
np.pi

3.141592653589793

OK back to arrays, which besides built in mathematical functions like square roots, exponentials, etc., are one of the most common uses of the numpy library.

Formally, an array is a collection of objects that all have the same type: a collection of integers, or floats, or bools, or anything else. In the simplest case, these are simply arranged into a numbered list, one after another. Think of an array as a box with a bunch of numbered compartments, each of which can hold something. For example, here is a box with eight compartments.

![](https://drive.google.com/uc?export=view&id=1liecCBkXR30DXDrw6lnOkcLpoQQNJ9sE)

In python, and in many (but not all) computer languages, we start counting at 0, so that the first compartment is compartment 0, the second is compartment 1, and so forth. We can create an array in python in a few different ways. One is just to explicitly list the elements we want it to contain. The syntax is straightforward:

In [44]:
x = np.array([10,11,12,13,14,15,16,17])

This puts the values we specified into the appropriate compartments in the box. The array x can be thought of like this:

![](https://drive.google.com/uc?export=view&id=1Pcu4VtKtojLGa3Mkx9fHkXpkNPHeWiTe)

note that there is no output here, because again we are defining a variable. You can see it and check the stored values by typing the variable name.

In [45]:
x

array([10, 11, 12, 13, 14, 15, 16, 17])

If you type the array you've defined, you'll also see that is is a special new kind of numpy variable.

In [46]:
type(x)

numpy.ndarray

*For those of you who have used python before, note that an array is different from a list (defined simply with square brackets, e.g. a = [1,2,3,4,5]). There are some subtle differences between the two, but the principal practical difference is that you can do arithmetic operations on arrays, but not lists.*

In this case the array we have created is an array of integers, since each of the entries we specified was an integer. If one of them had been a floating point number (for example if we changed the 10 to 10.0), then the array would have been an array of floats, meaning that EACH entry would have been made a float. Remember the rule: every element of an array must have the same type, so if you make one them into a float, then all of them will be floats.

Another way to create an array is to simply give the number of elements, and set them all to be zero initially. This can be done with the zeros command:

In [47]:
y = np.zeros(8)
y

array([0., 0., 0., 0., 0., 0., 0., 0.])

The zeros command creates an array with the specified number of elements, and sets them all to zero. Note that they are all floats (you can tell from the decimal point after each zero), which is what the zeros command creates by default. If you want some other data type, you can specify it using an option built into the zeros command called "dtype", which allows you to specify the data type you want:

In [48]:
yint = np.zeros(8, dtype='int')
yint

array([0, 0, 0, 0, 0, 0, 0, 0])

<div class=sidebar>

### Sidebar - Function options/keywords
-----------------------

Say you know you want to use the numpy function zeros to define an integer array, but you can't remember the syntax for the option, its name, etc. To find out what is available, you can use one of the special functions of a Jupyter code cell by following the function name with a question mark, as below:

In [49]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

<div class=sidebar>
This prints the function's "docstring". This docstring will list the available options (keywords), and will often give examples of their usage. A good descriptive docstring is a very important part of writing functions, as we will discuss in detail next week.

The analogous numpy function "ones" creates an array where every element is 1. Here too, the default data type is float.

In [50]:
z = np.ones(8)
z

array([1., 1., 1., 1., 1., 1., 1., 1.])

A third and very useful way to create arrays is using the arange command. This creates an array with specified starting and ending values, and with a specified step size. For example:

In [51]:
w = np.arange(0,16,2)
w

array([ 0,  2,  4,  6,  8, 10, 12, 14])

The first argument to arange is the starting value, the second is the ending value (notice that this is exclusive, not inclusive, so in the above example the array z does not contain the number 16), and the final entry is the step size.

Again, because all the entries were integers, the array consists of integers. If one of them had been a float, the array would have contained floats.

Note that one can omit the final entry in arange, in which case the step size defaults to a value of 1. One can also omit the second entry (for example just say arange(8)), in which case the array created starts with 0 as the first entry, has a step size of 1, and contains the number of entries specified in the argument. Thus arange(8) creates an array that contains the numbers 0 to 7.

In [52]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

### 4.2 Array Manipulation

So how do we deal with arrays? What can we do with them?

One way to deal with an array is to interact with its elements individually. We can do that by specifying their index, which designates which compartment in the box we want to access. We can then print out values, alter them, or do any other operation on them we could do with a simple number. The way we index an array is by putting a number in square brackets after it. For example:

In [53]:
x[2]

np.int64(12)

In [54]:
type(x[2])

numpy.int64

In [55]:
x[2]*2

np.int64(24)

In [56]:
x[2] = 32
x

array([10, 11, 32, 13, 14, 15, 16, 17])

In the examples above, we printed out the value stored in compartment number 2 of the array x, we checked the type of value stored in that compartment (in this case, a 64 bit integer), we multiplied it by 2 to get a result, and then we assigned a different value (32) to that compartment, erasing its original value.

So why are arrays more useful than just individual variables? There are a number of reasons, but one of the most important is called broadcasting, meaning that we can access, perform arithmetic with, and alter multiple elements of an array at once. We specify parts of an array by giving a range of indices in the square brackets, separated by a colon. For example,

In [57]:
x[1:4]

array([11, 32, 13])

Here the number before the colon specifies the starting index, and the number after the colon specifies the ending index; **this is exclusive, not inclusive, so the ending index element is not included**. If we omit the number before the colon, the region of the array we are referring to is assumed to start from element 0, and if we omit the number after the colon, it is assumed to end at the last element, as below:

In [58]:
x[:4]

array([10, 11, 32, 13])

In [59]:
x[4:]

array([14, 15, 16, 17])

We can also specify that we want not every element, but every 2nd element, or every 3rd element, etc., within our specified range. For example:

In [60]:
x[::2]

array([10, 32, 14, 16])

Here the empty space before the first colon says to start at element 0, the empty space between the first and second colons says to end at the end of the array, and the number 2 after the colon says to access every 2nd element, rather than every element, which is the default.

Finally, array indices can be specified either as positive numbers, which count from the beginning, or as negative numbers, which count from the end. The last element is -1, the second to last is -2, and so forth, as shown below:

![](https://drive.google.com/uc?export=view&id=1aHrZpmzcacTnlE76kCQWT75KIXGMRV7g)

This is convenient, for example, if one wants to refer to all but the last 2 elements of an array:

In [61]:
x[:-2]

array([10, 11, 32, 13, 14, 15])

The really useful thing is that one can use this capability to perform mathematical operations or assignments to multiple elements of an array at once. Several examples are given below. Execute the cell, examine the output, and make sure you understand what happened to the array before moving on.

In [62]:
x-10

array([ 0,  1, 22,  3,  4,  5,  6,  7])

In [63]:
x[1:4]-10

array([ 1, 22,  3])

In [64]:
x[1:4]=-10
x

array([ 10, -10, -10, -10,  14,  15,  16,  17])

In [65]:
x[::2]=5
x

array([  5, -10,   5, -10,   5,  15,   5,  17])

One can also do operations involving two arrays with the same number of elements. These operations are performed element by element. For example:

In [66]:
arr1 = np.arange(10)

In [67]:
arr2 = np.arange(10)*2

In [68]:
arr1 + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In this example, x is filled with 0, 1, 2, ... 9, and y is filled with 0, 2, 4, ... 18. When we add them, we get 0, 3, 6, ... 27. The arrays are added together one element at a time, producing an output array that has the same number of elements as the two inputs.

These capabilities for manipulating multiple elements at once are very convenient for manipulating large groups of numbers.

### 4.3 Multidimensional arrays

The arrays we've played with so far are one-dimensional, meaning that they look like a series of boxes laid out in a line. However, arrays can be multidimensional as well. For example:

In [69]:
x2d = np.array([[10,11,12,13,14,15,16,17], [20,21,22,23,24,25,26,27], [30, 31, 32, 33, 34, 35, 36, 37]])
x2d

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [20, 21, 22, 23, 24, 25, 26, 27],
       [30, 31, 32, 33, 34, 35, 36, 37]])

You can think of this as a box with multiple rows of compartments:

![](https://drive.google.com/uc?export=view&id=1yijbZjKoJRtYVYA099KlAc_wwiKq8Kj5)

The zeros and ones commands also work in multiple dimensions. You just have to specify the size of each dimension:

In [70]:
y2d = np.zeros((3,7))
y2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Similarly, one can index multi-dimensional arrays just by indexing each dimension in turn. Execute each of the cells below and make sure you understand what it is doing.

In [71]:
x2d[0,0]

np.int64(10)

In [72]:
x2d[0,:]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [73]:
x2d[:,1]

array([11, 21, 31])

In [74]:
x2d[:,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Arrays can of course have more than two dimensions as well. In fact, there is no limit to how many dimensions they can have.

You can also do useful things like find the maximum and minimum values in arrays, and their means and totals:

In [75]:
np.amin(x2d)

np.int64(10)

In [76]:
np.amax(x2d)

np.int64(37)

In [77]:
np.mean(x2d)

np.float64(23.5)

In [78]:
np.sum(x2d)

np.int64(564)

### 4.4 Array Attributes

Much of astronomy is image manipulation, and images are essentially very large arrays (large enough that it no longer becomes practical to print them to the window as we've been doing here). Upon importing an array (e.g. an astronomical image) or after manipulating it, you will often want to know some of its basic properties. There are several built-in python functions that are particularly useful for this, and you call them by typing the variable name + the operator name, as below.

In [79]:
x2d.ndim

2

In [80]:
x2d.shape

(3, 8)

In [81]:
x2d.size

24

In [82]:
x2d.dtype

dtype('int64')

<div class=hw>

### Exercise 4

-------------

Follow the steps below.

1) Create a 10 x 10 numpy integer array and set it equal to a variable. Print it to output once you're done populating it as described below. **Try to do this with as little hard-coding as possible! (i.e., don't just type out each array entry - use array indexing, np.zeros/np.ones, array operations, etc.)**
  * make the first row (row 0) contain the numbers 1 through 10 in order  
  * make each element in the second row (row 1) equal to 1 more than the first row (row 0)
  * row 2 = row 0\*10  
  * row 3 = (row 0)$^2$  
  * row 4 = $\sqrt{row 1}$  
  * row 5 = 3\*(row 2)-2\*(row 3)
  * row 6 = alternating 0s and 1s, starting with 1
  * row 7 = all 8s except the third from last element, which is -8
  * row 8 = 1, 1/2, 1/3, 1/4, ...
  * row 9 = all elements are 42

2) copy this array into a new variable, then in the new array, multiply each number in the third column (column 2) by two  
3) set the second to last element in each row of the new array equal to 0, and print the new array as output  
4) multiply your original array by this new array and print the output  

In [83]:
#execute this cell before beginning so that the array will be more readable when you print it
np.set_printoptions(precision=3, suppress=True, linewidth=120)

In [84]:
ar1 = np.zeros((10,10))
ar1[0] = np.arange(1, 11)
ar1[1] = ar1[0]+1
ar1[2] = ar1[0]*10
ar1[3] = ar1[0]**2
ar1[4] = np.sqrt(ar1[1])
ar1[5] = 3*ar1[2]-2*ar1[3]
ar1[6][::2] = 1
ar1[7] = 8
ar1[7, -1] = -8
ar1[8] = ar1[0]**(-1)
ar1[9] = 42
print(ar1, "\n")

ar2 = ar1
ar2[:,2] = ar2[:,2]*2
ar2[:,-2] = 0
print(ar2, "\n")

print(ar1*ar2)

[[  1.      2.      3.      4.      5.      6.      7.      8.      9.     10.   ]
 [  2.      3.      4.      5.      6.      7.      8.      9.     10.     11.   ]
 [ 10.     20.     30.     40.     50.     60.     70.     80.     90.    100.   ]
 [  1.      4.      9.     16.     25.     36.     49.     64.     81.    100.   ]
 [  1.414   1.732   2.      2.236   2.449   2.646   2.828   3.      3.162   3.317]
 [ 28.     52.     72.     88.    100.    108.    112.    112.    108.    100.   ]
 [  1.      0.      1.      0.      1.      0.      1.      0.      1.      0.   ]
 [  8.      8.      8.      8.      8.      8.      8.      8.      8.     -8.   ]
 [  1.      0.5     0.333   0.25    0.2     0.167   0.143   0.125   0.111   0.1  ]
 [ 42.     42.     42.     42.     42.     42.     42.     42.     42.     42.   ]] 

[[  1.      2.      6.      4.      5.      6.      7.      8.      0.     10.   ]
 [  2.      3.      8.      5.      6.      7.      8.      9.      0.     11.   ]
 

In addition to the capabilities we've just gone through, arrays can do far more. For a full list, see http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html.

## Submission Instructions

Before submitting any Jupyter notebook for grading, please follow the following steps

**1) Hit the "Restart the kernel run the whole notebook" button.**

Make sure the entire notebook runs from start to finish. If necessary, comment out any un-executable cells from the instructions portion of the lab so the whole notebook will execute in one go.

**2) Save as PDF (easiest method is with File > Print... > Save as PDF).**

**3) If applicable, make sure the names of all group members are in a markdown cell at the top of the file and submit the notebook through the Gradescope link. For this assignment, you should work individually, and thus should not have any group members (although please feel free to ask questions to your peers!)**

For this assignment, please submit all three Jupyter notebooks as PDFs (along with Part 2 of Homework 00) to the same Gradescope link.